//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMSHost.SendUMSMessage_NS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendUMSMessage_NS.ISendUMSMessage")]
    public interface ISendUMSMessage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Hello", ReplyAction="http://tempuri.org/ISendUMSMessage/HelloResponse")]
        void Hello(string srcName, string env);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Hello", ReplyAction="http://tempuri.org/ISendUMSMessage/HelloResponse")]
        System.Threading.Tasks.Task HelloAsync(string srcName, string env);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Send", ReplyAction="http://tempuri.org/ISendUMSMessage/SendResponse")]
        void Send(string srcName, string env, string name, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Send", ReplyAction="http://tempuri.org/ISendUMSMessage/SendResponse")]
        System.Threading.Tasks.Task SendAsync(string srcName, string env, string name, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendCL", ReplyAction="http://tempuri.org/ISendUMSMessage/SendCLResponse")]
        void SendCL(string srcName, string env, string name, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendCL", ReplyAction="http://tempuri.org/ISendUMSMessage/SendCLResponse")]
        System.Threading.Tasks.Task SendCLAsync(string srcName, string env, string name, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendToForm", ReplyAction="http://tempuri.org/ISendUMSMessage/SendToFormResponse")]
        void SendToForm(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendToForm", ReplyAction="http://tempuri.org/ISendUMSMessage/SendToFormResponse")]
        System.Threading.Tasks.Task SendToFormAsync(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendToForm2", ReplyAction="http://tempuri.org/ISendUMSMessage/SendToForm2Response")]
        void SendToForm2(string uiID, string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendToForm2", ReplyAction="http://tempuri.org/ISendUMSMessage/SendToForm2Response")]
        System.Threading.Tasks.Task SendToForm2Async(string uiID, string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendAll", ReplyAction="http://tempuri.org/ISendUMSMessage/SendAllResponse")]
        void SendAll(string srcName, string env, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendAll", ReplyAction="http://tempuri.org/ISendUMSMessage/SendAllResponse")]
        System.Threading.Tasks.Task SendAllAsync(string srcName, string env, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendList", ReplyAction="http://tempuri.org/ISendUMSMessage/SendListResponse")]
        void SendList(string srcName, string env, string[] nameList, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendList", ReplyAction="http://tempuri.org/ISendUMSMessage/SendListResponse")]
        System.Threading.Tasks.Task SendListAsync(string srcName, string env, string[] nameList, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SetClient", ReplyAction="http://tempuri.org/ISendUMSMessage/SetClientResponse")]
        void SetClient(string pass2UserID, string env, string macAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SetClient", ReplyAction="http://tempuri.org/ISendUMSMessage/SetClientResponse")]
        System.Threading.Tasks.Task SetClientAsync(string pass2UserID, string env, string macAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/KeszreJelentes", ReplyAction="http://tempuri.org/ISendUMSMessage/KeszreJelentesResponse")]
        void KeszreJelentes(string macAddress, int sound, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/KeszreJelentes", ReplyAction="http://tempuri.org/ISendUMSMessage/KeszreJelentesResponse")]
        System.Threading.Tasks.Task KeszreJelentesAsync(string macAddress, int sound, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Vontat", ReplyAction="http://tempuri.org/ISendUMSMessage/VontatResponse")]
        void Vontat(string macAddress, int sound, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Vontat", ReplyAction="http://tempuri.org/ISendUMSMessage/VontatResponse")]
        System.Threading.Tasks.Task VontatAsync(string macAddress, int sound, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/PASS2Message", ReplyAction="http://tempuri.org/ISendUMSMessage/PASS2MessageResponse")]
        void PASS2Message(string srcName, string env, string app, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/PASS2Message", ReplyAction="http://tempuri.org/ISendUMSMessage/PASS2MessageResponse")]
        System.Threading.Tasks.Task PASS2MessageAsync(string srcName, string env, string app, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/PASS2MessageCL", ReplyAction="http://tempuri.org/ISendUMSMessage/PASS2MessageCLResponse")]
        void PASS2MessageCL(string srcName, string env, string pass2ID, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/PASS2MessageCL", ReplyAction="http://tempuri.org/ISendUMSMessage/PASS2MessageCLResponse")]
        System.Threading.Tasks.Task PASS2MessageCLAsync(string srcName, string env, string pass2ID, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/For00FormOpen", ReplyAction="http://tempuri.org/ISendUMSMessage/For00FormOpenResponse")]
        void For00FormOpen(string targetUser, string env, bool modal, string formName, string extraJsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/For00FormOpen", ReplyAction="http://tempuri.org/ISendUMSMessage/For00FormOpenResponse")]
        System.Threading.Tasks.Task For00FormOpenAsync(string targetUser, string env, bool modal, string formName, string extraJsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/For00FormOpenCL", ReplyAction="http://tempuri.org/ISendUMSMessage/For00FormOpenCLResponse")]
        void For00FormOpenCL(string targetUser, string env, bool modal, string formName, string extraJsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/For00FormOpenCL", ReplyAction="http://tempuri.org/ISendUMSMessage/For00FormOpenCLResponse")]
        System.Threading.Tasks.Task For00FormOpenCLAsync(string targetUser, string env, bool modal, string formName, string extraJsonData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendUMSMessageChannel : UMSHost.SendUMSMessage_NS.ISendUMSMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendUMSMessageClient : System.ServiceModel.ClientBase<UMSHost.SendUMSMessage_NS.ISendUMSMessage>, UMSHost.SendUMSMessage_NS.ISendUMSMessage {
        
        public SendUMSMessageClient() {
        }
        
        public SendUMSMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendUMSMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendUMSMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendUMSMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Hello(string srcName, string env) {
            base.Channel.Hello(srcName, env);
        }
        
        public System.Threading.Tasks.Task HelloAsync(string srcName, string env) {
            return base.Channel.HelloAsync(srcName, env);
        }
        
        public void Send(string srcName, string env, string name, string message) {
            base.Channel.Send(srcName, env, name, message);
        }
        
        public System.Threading.Tasks.Task SendAsync(string srcName, string env, string name, string message) {
            return base.Channel.SendAsync(srcName, env, name, message);
        }
        
        public void SendCL(string srcName, string env, string name, string message) {
            base.Channel.SendCL(srcName, env, name, message);
        }
        
        public System.Threading.Tasks.Task SendCLAsync(string srcName, string env, string name, string message) {
            return base.Channel.SendCLAsync(srcName, env, name, message);
        }
        
        public void SendToForm(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage) {
            base.Channel.SendToForm(srcName, env, name, formTypeID, publicMessage, privateMessage);
        }
        
        public System.Threading.Tasks.Task SendToFormAsync(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage) {
            return base.Channel.SendToFormAsync(srcName, env, name, formTypeID, publicMessage, privateMessage);
        }
        
        public void SendToForm2(string uiID, string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage) {
            base.Channel.SendToForm2(uiID, srcName, env, name, formTypeID, publicMessage, privateMessage);
        }
        
        public System.Threading.Tasks.Task SendToForm2Async(string uiID, string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage) {
            return base.Channel.SendToForm2Async(uiID, srcName, env, name, formTypeID, publicMessage, privateMessage);
        }
        
        public void SendAll(string srcName, string env, string message) {
            base.Channel.SendAll(srcName, env, message);
        }
        
        public System.Threading.Tasks.Task SendAllAsync(string srcName, string env, string message) {
            return base.Channel.SendAllAsync(srcName, env, message);
        }
        
        public void SendList(string srcName, string env, string[] nameList, string message) {
            base.Channel.SendList(srcName, env, nameList, message);
        }
        
        public System.Threading.Tasks.Task SendListAsync(string srcName, string env, string[] nameList, string message) {
            return base.Channel.SendListAsync(srcName, env, nameList, message);
        }
        
        public void SetClient(string pass2UserID, string env, string macAddress) {
            base.Channel.SetClient(pass2UserID, env, macAddress);
        }
        
        public System.Threading.Tasks.Task SetClientAsync(string pass2UserID, string env, string macAddress) {
            return base.Channel.SetClientAsync(pass2UserID, env, macAddress);
        }
        
        public void KeszreJelentes(string macAddress, int sound, string message) {
            base.Channel.KeszreJelentes(macAddress, sound, message);
        }
        
        public System.Threading.Tasks.Task KeszreJelentesAsync(string macAddress, int sound, string message) {
            return base.Channel.KeszreJelentesAsync(macAddress, sound, message);
        }
        
        public void Vontat(string macAddress, int sound, string message) {
            base.Channel.Vontat(macAddress, sound, message);
        }
        
        public System.Threading.Tasks.Task VontatAsync(string macAddress, int sound, string message) {
            return base.Channel.VontatAsync(macAddress, sound, message);
        }
        
        public void PASS2Message(string srcName, string env, string app, string message) {
            base.Channel.PASS2Message(srcName, env, app, message);
        }
        
        public System.Threading.Tasks.Task PASS2MessageAsync(string srcName, string env, string app, string message) {
            return base.Channel.PASS2MessageAsync(srcName, env, app, message);
        }
        
        public void PASS2MessageCL(string srcName, string env, string pass2ID, string message) {
            base.Channel.PASS2MessageCL(srcName, env, pass2ID, message);
        }
        
        public System.Threading.Tasks.Task PASS2MessageCLAsync(string srcName, string env, string pass2ID, string message) {
            return base.Channel.PASS2MessageCLAsync(srcName, env, pass2ID, message);
        }
        
        public void For00FormOpen(string targetUser, string env, bool modal, string formName, string extraJsonData) {
            base.Channel.For00FormOpen(targetUser, env, modal, formName, extraJsonData);
        }
        
        public System.Threading.Tasks.Task For00FormOpenAsync(string targetUser, string env, bool modal, string formName, string extraJsonData) {
            return base.Channel.For00FormOpenAsync(targetUser, env, modal, formName, extraJsonData);
        }
        
        public void For00FormOpenCL(string targetUser, string env, bool modal, string formName, string extraJsonData) {
            base.Channel.For00FormOpenCL(targetUser, env, modal, formName, extraJsonData);
        }
        
        public System.Threading.Tasks.Task For00FormOpenCLAsync(string targetUser, string env, bool modal, string formName, string extraJsonData) {
            return base.Channel.For00FormOpenCLAsync(targetUser, env, modal, formName, extraJsonData);
        }
    }
}
