//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.SendUMSMessage
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendUMSMessage.ISendUMSMessage")]
    public interface ISendUMSMessage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Hello", ReplyAction="http://tempuri.org/ISendUMSMessage/HelloResponse")]
        void Hello(string srcName, string env);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Hello", ReplyAction="http://tempuri.org/ISendUMSMessage/HelloResponse")]
        System.Threading.Tasks.Task HelloAsync(string srcName, string env);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Send", ReplyAction="http://tempuri.org/ISendUMSMessage/SendResponse")]
        void Send(string srcName, string env, string name, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/Send", ReplyAction="http://tempuri.org/ISendUMSMessage/SendResponse")]
        System.Threading.Tasks.Task SendAsync(string srcName, string env, string name, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendToForm", ReplyAction="http://tempuri.org/ISendUMSMessage/SendToFormResponse")]
        void SendToForm(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendToForm", ReplyAction="http://tempuri.org/ISendUMSMessage/SendToFormResponse")]
        System.Threading.Tasks.Task SendToFormAsync(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendAll", ReplyAction="http://tempuri.org/ISendUMSMessage/SendAllResponse")]
        void SendAll(string srcName, string env, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendAll", ReplyAction="http://tempuri.org/ISendUMSMessage/SendAllResponse")]
        System.Threading.Tasks.Task SendAllAsync(string srcName, string env, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendList", ReplyAction="http://tempuri.org/ISendUMSMessage/SendListResponse")]
        void SendList(string srcName, string env, string[] nameList, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SendList", ReplyAction="http://tempuri.org/ISendUMSMessage/SendListResponse")]
        System.Threading.Tasks.Task SendListAsync(string srcName, string env, string[] nameList, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SetClient", ReplyAction="http://tempuri.org/ISendUMSMessage/SetClientResponse")]
        void SetClient(string pass2UserID, string env);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendUMSMessage/SetClient", ReplyAction="http://tempuri.org/ISendUMSMessage/SetClientResponse")]
        System.Threading.Tasks.Task SetClientAsync(string pass2UserID, string env);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendUMSMessageChannel : Services.SendUMSMessage.ISendUMSMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendUMSMessageClient : System.ServiceModel.ClientBase<Services.SendUMSMessage.ISendUMSMessage>, Services.SendUMSMessage.ISendUMSMessage {
        
        public SendUMSMessageClient() {
        }
        
        public SendUMSMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendUMSMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendUMSMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendUMSMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Hello(string srcName, string env) {
            base.Channel.Hello(srcName, env);
        }
        
        public System.Threading.Tasks.Task HelloAsync(string srcName, string env) {
            return base.Channel.HelloAsync(srcName, env);
        }
        
        public void Send(string srcName, string env, string name, string message) {
            base.Channel.Send(srcName, env, name, message);
        }
        
        public System.Threading.Tasks.Task SendAsync(string srcName, string env, string name, string message) {
            return base.Channel.SendAsync(srcName, env, name, message);
        }
        
        public void SendToForm(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage) {
            base.Channel.SendToForm(srcName, env, name, formTypeID, publicMessage, privateMessage);
        }
        
        public System.Threading.Tasks.Task SendToFormAsync(string srcName, string env, string name, string formTypeID, string publicMessage, string privateMessage) {
            return base.Channel.SendToFormAsync(srcName, env, name, formTypeID, publicMessage, privateMessage);
        }
        
        public void SendAll(string srcName, string env, string message) {
            base.Channel.SendAll(srcName, env, message);
        }
        
        public System.Threading.Tasks.Task SendAllAsync(string srcName, string env, string message) {
            return base.Channel.SendAllAsync(srcName, env, message);
        }
        
        public void SendList(string srcName, string env, string[] nameList, string message) {
            base.Channel.SendList(srcName, env, nameList, message);
        }
        
        public System.Threading.Tasks.Task SendListAsync(string srcName, string env, string[] nameList, string message) {
            return base.Channel.SendListAsync(srcName, env, nameList, message);
        }
        
        public void SetClient(string pass2UserID, string env) {
            base.Channel.SetClient(pass2UserID, env);
        }
        
        public System.Threading.Tasks.Task SetClientAsync(string pass2UserID, string env) {
            return base.Channel.SetClientAsync(pass2UserID, env);
        }
    }
}
