#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVI.ARCH.UMS.DAL_NS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DV01_IFP")]
	public partial class UmsSchemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public UmsSchemaDataContext() : 
				base("Data Source=tadsqlpas3.tad.mavinformatika.hu;Initial Catalog=DV01_IFP;Integrated " +
						"Security=True", mappingSource)
		{
			OnCreated();
		}
		
		public UmsSchemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UmsSchemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UmsSchemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UmsSchemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_addUserInfo")]
		public int usp_addUserInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string connectionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string pass2UserID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string environmentName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string macAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), connectionID, pass2UserID, environmentName, macAddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_delUserInfo")]
		public int usp_delUserInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string connectionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), connectionID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_getUserInfoByConnectionId")]
		public ISingleResult<usp_getUserInfoByConnectionIdResult> usp_getUserInfoByConnectionId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string connectionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), connectionId);
			return ((ISingleResult<usp_getUserInfoByConnectionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_getUserInfoByMacAddress")]
		public ISingleResult<usp_getUserInfoByMacAddressResult> usp_getUserInfoByMacAddress([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string macAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), macAddress);
			return ((ISingleResult<usp_getUserInfoByMacAddressResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_getUserInfoByPass2UserId")]
		public ISingleResult<usp_getUserInfoByPass2UserIdResult> usp_getUserInfoByPass2UserId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string pass2UserID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pass2UserID);
			return ((ISingleResult<usp_getUserInfoByPass2UserIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_setMessage")]
		public int usp_setMessage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string connectionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string sender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), connectionID, sender, message);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_setPass2Info")]
		public int usp_setPass2Info([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string connectionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string pass2UserID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string environmentName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string machineName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string macAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), connectionID, pass2UserID, environmentName, machineName, macAddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="UMS.usp_getPass2UserIdListByApp")]
		public ISingleResult<usp_getPass2UserIdListByAppResult> usp_getPass2UserIdListByApp([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> app)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), app);
			return ((ISingleResult<usp_getPass2UserIdListByAppResult>)(result.ReturnValue));
		}
	}
	
	public partial class usp_getUserInfoByConnectionIdResult
	{
		
		private string _SignalRConnectionID;
		
		private string _Pass2UserID;
		
		private string _MACAddress;
		
		private string _LastMessageSender;
		
		private System.Nullable<System.DateTime> _ConnectionStarted;
		
		private string _EnvironmentName;
		
		private string _MachineName;
		
		private System.Nullable<System.DateTime> _LastMessageTime;
		
		private string _LastMessageText;
		
		public usp_getUserInfoByConnectionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignalRConnectionID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SignalRConnectionID
		{
			get
			{
				return this._SignalRConnectionID;
			}
			set
			{
				if ((this._SignalRConnectionID != value))
				{
					this._SignalRConnectionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass2UserID", DbType="VarChar(100)")]
		public string Pass2UserID
		{
			get
			{
				return this._Pass2UserID;
			}
			set
			{
				if ((this._Pass2UserID != value))
				{
					this._Pass2UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAddress", DbType="VarChar(17)")]
		public string MACAddress
		{
			get
			{
				return this._MACAddress;
			}
			set
			{
				if ((this._MACAddress != value))
				{
					this._MACAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageSender", DbType="VarChar(100)")]
		public string LastMessageSender
		{
			get
			{
				return this._LastMessageSender;
			}
			set
			{
				if ((this._LastMessageSender != value))
				{
					this._LastMessageSender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionStarted", DbType="DateTime")]
		public System.Nullable<System.DateTime> ConnectionStarted
		{
			get
			{
				return this._ConnectionStarted;
			}
			set
			{
				if ((this._ConnectionStarted != value))
				{
					this._ConnectionStarted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvironmentName", DbType="VarChar(50)")]
		public string EnvironmentName
		{
			get
			{
				return this._EnvironmentName;
			}
			set
			{
				if ((this._EnvironmentName != value))
				{
					this._EnvironmentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(50)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastMessageTime
		{
			get
			{
				return this._LastMessageTime;
			}
			set
			{
				if ((this._LastMessageTime != value))
				{
					this._LastMessageTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageText", DbType="NVarChar(MAX)")]
		public string LastMessageText
		{
			get
			{
				return this._LastMessageText;
			}
			set
			{
				if ((this._LastMessageText != value))
				{
					this._LastMessageText = value;
				}
			}
		}
	}
	
	public partial class usp_getUserInfoByMacAddressResult
	{
		
		private string _SignalRConnectionID;
		
		private string _Pass2UserID;
		
		private string _MACAddress;
		
		private string _LastMessageSender;
		
		private System.Nullable<System.DateTime> _ConnectionStarted;
		
		private string _EnvironmentName;
		
		private string _MachineName;
		
		private System.Nullable<System.DateTime> _LastMessageTime;
		
		private string _LastMessageText;
		
		public usp_getUserInfoByMacAddressResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignalRConnectionID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SignalRConnectionID
		{
			get
			{
				return this._SignalRConnectionID;
			}
			set
			{
				if ((this._SignalRConnectionID != value))
				{
					this._SignalRConnectionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass2UserID", DbType="VarChar(100)")]
		public string Pass2UserID
		{
			get
			{
				return this._Pass2UserID;
			}
			set
			{
				if ((this._Pass2UserID != value))
				{
					this._Pass2UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAddress", DbType="VarChar(17)")]
		public string MACAddress
		{
			get
			{
				return this._MACAddress;
			}
			set
			{
				if ((this._MACAddress != value))
				{
					this._MACAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageSender", DbType="VarChar(100)")]
		public string LastMessageSender
		{
			get
			{
				return this._LastMessageSender;
			}
			set
			{
				if ((this._LastMessageSender != value))
				{
					this._LastMessageSender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionStarted", DbType="DateTime")]
		public System.Nullable<System.DateTime> ConnectionStarted
		{
			get
			{
				return this._ConnectionStarted;
			}
			set
			{
				if ((this._ConnectionStarted != value))
				{
					this._ConnectionStarted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvironmentName", DbType="VarChar(50)")]
		public string EnvironmentName
		{
			get
			{
				return this._EnvironmentName;
			}
			set
			{
				if ((this._EnvironmentName != value))
				{
					this._EnvironmentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(50)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastMessageTime
		{
			get
			{
				return this._LastMessageTime;
			}
			set
			{
				if ((this._LastMessageTime != value))
				{
					this._LastMessageTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageText", DbType="NVarChar(MAX)")]
		public string LastMessageText
		{
			get
			{
				return this._LastMessageText;
			}
			set
			{
				if ((this._LastMessageText != value))
				{
					this._LastMessageText = value;
				}
			}
		}
	}
	
	public partial class usp_getUserInfoByPass2UserIdResult
	{
		
		private string _SignalRConnectionID;
		
		private string _Pass2UserID;
		
		private string _MACAddress;
		
		private string _LastMessageSender;
		
		private System.Nullable<System.DateTime> _ConnectionStarted;
		
		private string _EnvironmentName;
		
		private string _MachineName;
		
		private System.Nullable<System.DateTime> _LastMessageTime;
		
		private string _LastMessageText;
		
		public usp_getUserInfoByPass2UserIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignalRConnectionID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SignalRConnectionID
		{
			get
			{
				return this._SignalRConnectionID;
			}
			set
			{
				if ((this._SignalRConnectionID != value))
				{
					this._SignalRConnectionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass2UserID", DbType="VarChar(100)")]
		public string Pass2UserID
		{
			get
			{
				return this._Pass2UserID;
			}
			set
			{
				if ((this._Pass2UserID != value))
				{
					this._Pass2UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAddress", DbType="VarChar(17)")]
		public string MACAddress
		{
			get
			{
				return this._MACAddress;
			}
			set
			{
				if ((this._MACAddress != value))
				{
					this._MACAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageSender", DbType="VarChar(100)")]
		public string LastMessageSender
		{
			get
			{
				return this._LastMessageSender;
			}
			set
			{
				if ((this._LastMessageSender != value))
				{
					this._LastMessageSender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionStarted", DbType="DateTime")]
		public System.Nullable<System.DateTime> ConnectionStarted
		{
			get
			{
				return this._ConnectionStarted;
			}
			set
			{
				if ((this._ConnectionStarted != value))
				{
					this._ConnectionStarted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvironmentName", DbType="VarChar(50)")]
		public string EnvironmentName
		{
			get
			{
				return this._EnvironmentName;
			}
			set
			{
				if ((this._EnvironmentName != value))
				{
					this._EnvironmentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(50)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastMessageTime
		{
			get
			{
				return this._LastMessageTime;
			}
			set
			{
				if ((this._LastMessageTime != value))
				{
					this._LastMessageTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMessageText", DbType="NVarChar(MAX)")]
		public string LastMessageText
		{
			get
			{
				return this._LastMessageText;
			}
			set
			{
				if ((this._LastMessageText != value))
				{
					this._LastMessageText = value;
				}
			}
		}
	}
	
	public partial class usp_getPass2UserIdListByAppResult
	{
		
		private string _SignalRConnectionID;
		
		private string _Pass2UserID;
		
		private string _MachineName;
		
		private string _MACAddress;

        private string _EnvironmentName;

        public usp_getPass2UserIdListByAppResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignalRConnectionID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SignalRConnectionID
		{
			get
			{
				return this._SignalRConnectionID;
			}
			set
			{
				if ((this._SignalRConnectionID != value))
				{
					this._SignalRConnectionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass2UserID", DbType="VarChar(100)")]
		public string Pass2UserID
		{
			get
			{
				return this._Pass2UserID;
			}
			set
			{
				if ((this._Pass2UserID != value))
				{
					this._Pass2UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(50)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAddress", DbType="VarChar(17)")]
		public string MACAddress
		{
			get
			{
				return this._MACAddress;
			}
			set
			{
				if ((this._MACAddress != value))
				{
					this._MACAddress = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EnvironmentName", DbType = "VarChar(50)", CanBeNull = true)]
        public string EnvironmentName
        {
            get
            {
                return this._EnvironmentName;
            }
            set
            {
                if ((this._EnvironmentName != value))
                {
                    this._EnvironmentName = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
